<?php

namespace AppBundle\Repository;

/**
 * UserManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserManagerRepository extends \Doctrine\ORM\EntityRepository
{
}
