api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check
