# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    service_requette:
        class: ApiBundle\Service\ServiceGlobal
        arguments: [ "@doctrine.orm.entity_manager" ]
   # ApiBundle\:
    #    resource: '../src/Service/*'

    logic_services:
        class: ApiBundle\Service\LogicService
        arguments: [ "@doctrine.orm.entity_manager" ]


    mobile_services:
        class: ApiBundle\Service\MobileService
        arguments: [ "@doctrine.orm.entity_manager" ]
    
    search_services:
        class: ApiBundle\Service\SearchService
        arguments: [ "@doctrine.orm.entity_manager" ]
