<?php

namespace ApiBundle\Repository;

/**
 * ActivityUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityUserRepository extends \Doctrine\ORM\EntityRepository
{
}
