<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($keyword) {
        $qb = $this->createQueryBuilder('a');

            $qb->andWhere('a.name like :keyword or concat(a.type_activity,"")  like :keyword or concat(a.startDate,"") like :keyword or concat(a.endDate,"") like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');
       return $qb->getQuery();
    }
}
