<?php

namespace ApiBundle\Repository;

/**
 * POSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class POSRepository extends \Doctrine\ORM\EntityRepository
{
}
