<?php

namespace ApiBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByActivityId($idAct)
    {

            $qb = $this->createQueryBuilder('a');
            $qb->where('a.activity = :idAct')
            ->setParameter('idAct', $idAct)
            ->andWhere('a.status = :status')
            ->setParameter('status', true)
            ->orderBy('a.name', 'DESC');
            return $qb->getQuery()
            ->getResult();
    }
}
