<?php

namespace ApiBundle\Repository;

/**
 * ProductSurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSurveyRepository extends \Doctrine\ORM\EntityRepository
{
}
