<?php

namespace ApiBundle\Repository;

/**
 * QuarterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuarterRepository extends \Doctrine\ORM\EntityRepository
{
}
