<?php

namespace ApiBundle\Repository;

/**
 * TargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TargetRepository extends \Doctrine\ORM\EntityRepository
{
}
