<?php

namespace ApiBundle\Repository;

/**
 * TownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownRepository extends \Doctrine\ORM\EntityRepository
{
}
